import { db } from "./db.js";import type {PricePoint} from "./discovery/anomalyScanner.js";import {scanDiscoveryLibrary} from "./discovery/discoveryLibrary.js";import {freezeable,type HypothesisProposal} from "./discovery/hypothesisFactory.js";
const WINDOWS=[30,60,90,180],MAX=500;
async function main(){const {data,error}=await db.from("crypto_universe_snapshots").select("observed_at,asset,price_usd").gte("observed_at",new Date(Date.now()-180*86400_000).toISOString()).order("observed_at",{ascending:true});if(error)throw error;
 const all:Record<string,PricePoint[]>={};for(const r of data??[])(all[r.asset]??=[]).push({ts:r.observed_at,price:Number(r.price_usd)});
 const candidates:any[]=[];for(const days of WINDOWS){const cut=Date.now()-days*86400_000,series=Object.fromEntries(Object.entries(all).map(([a,s])=>[a,s.filter(x=>Date.parse(x.ts)>=cut)]));for(const h of scanDiscoveryLibrary(series))candidates.push({...h,campaignWindowDays:days})}
 candidates.sort((a,b)=>b.score-a.score);let proposed=0;
 for(const hit of candidates.slice(0,MAX)){const assetA=hit.leader??hit.asset;if(!assetA)continue;const assetB=hit.follower,pred=assetB??assetA,dir=hit.direction==="DOWN"?"SHORT":"LONG";
  const h:HypothesisProposal={generator:"historical_campaign",generatorVersion:"C1",market:"crypto",assetA,assetB,observationWindow:`${hit.windowHours}h`,claim:`${hit.family} historical campaign candidate on ${assetA}${assetB?` -> ${assetB}`:""}; test repeatable after-cost behavior.`,mechanism:"Machine-discovered historical anomaly; mechanism unproven.",triggerDefinition:{family:hit.family,direction:hit.direction??"STATE_CHANGE",windowHours:hit.windowHours,campaignWindowDays:hit.campaignWindowDays,features:hit.features},predictedEffect:{asset:pred,direction:dir,horizonsHours:[1,4,8,12,24]},falsificationCriteria:{holdoutRequired:true,forwardRequired:true,multipleTestingCorrectionRequired:true,netExpectancyMustBePositive:true},requiredData:[`${assetA} synchronized spot`,...(assetB?[`${assetB} synchronized spot`]:[]),"dynamic execution cost model"]};
  const f=freezeable(h);if(!f.valid||!f.key)continue;const {error:he}=await db.from("hypotheses").upsert({hypothesis_key:f.key,generator:h.generator,generator_version:h.generatorVersion,market:h.market,asset_a:h.assetA,asset_b:h.assetB??null,observation_window:h.observationWindow,claim:h.claim,mechanism:h.mechanism,trigger_definition:h.triggerDefinition,predicted_effect:h.predictedEffect,falsification_criteria:h.falsificationCriteria,required_data:h.requiredData,status:"PROPOSED",discovery_evidence:{campaign:"031",searchWindowsDays:WINDOWS,totalCandidates:candidates.length,hit},test_version:"C1.0"},{onConflict:"hypothesis_key",ignoreDuplicates:true});if(he)throw he;proposed++}
 console.log(JSON.stringify({ok:true,build:"031",observations:(data??[]).length,rawCandidates:candidates.length,topConsidered:Math.min(MAX,candidates.length),hypothesesConsidered:proposed,searchWindowsDays:WINDOWS,authorizedToTrade:false},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
