import { db } from "./db.js";import {volumeTrigger,type VolumePoint} from "./discovery/volumeLibrary.js";
import { mean, ret, singleEvents, pairEvents, type Pt } from "./science/priceEvents.js";
type H={id:string;hypothesis_key:string;asset_a:string;asset_b:string|null;trigger_definition:any;predicted_effect:any;status:string};
// Build 041: Supabase returns at most 1,000 rows per request, so both loaders page
// through results. Prices come only from the Coinbase historical backfill (HIST-028):
// live snapshots (U1) use a different timestamp convention and must not be mixed in.
const PAGE=1000;
async function series(asset:string,start:string,end:string):Promise<Pt[]>{const rows:any[]=[];for(let f=0;;f+=PAGE){const {data,error}=await db.from("crypto_universe_snapshots").select("observed_at,price_usd").eq("asset",asset).eq("sensor_version","HIST-028").gte("observed_at",start).lte("observed_at",end).order("observed_at",{ascending:true}).range(f,f+PAGE-1);if(error)throw error;rows.push(...(data??[]));if((data??[]).length<PAGE)break}return rows.map(x=>({t:Date.parse(x.observed_at),p:Number(x.price_usd)}))}
async function volumeSeries(asset:string,start:string,end:string){const rows:any[]=[];for(let f=0;;f+=PAGE){const {data,error}=await db.from("market_volume_observations").select("observed_at,volume_base").eq("asset",asset).eq("sensor_version","VOL035").gte("observed_at",start).lte("observed_at",end).order("observed_at",{ascending:true}).range(f,f+PAGE-1);if(error)throw error;rows.push(...(data??[]));if((data??[]).length<PAGE)break}return rows}
async function test(h:H){const end=new Date().toISOString(),start=new Date(Date.now()-180*24*3600_000).toISOString(),a=await series(h.asset_a,start,end),horizons=[1,4,8,12,24],b=h.asset_b?await series(h.asset_b,start,end):null,results:any={};let best:any=null;
 for(const hz of horizons){const vals=b?pairEvents(h.trigger_definition?.family,a,b,hz):singleEvents(h.trigger_definition?.family,a,hz),mu=mean(vals);results[hz]={n:vals.length,meanDirectionalReturn:mu,winRate:vals.length?vals.filter(x=>x>0).length/vals.length:null};if(vals.length>=30&&mu!=null&&(!best||mu>best.meanDirectionalReturn))best={horizon:hz,n:vals.length,meanDirectionalReturn:mu,winRate:results[hz].winRate}}
 if(["VOLUME_SPIKE","MOMENTUM_VOLUME_CONFIRMATION","MOMENTUM_VOLUME_DIVERGENCE","VOLUME_PRECEDES_PRICE"].includes(h.trigger_definition?.family)){const v=await volumeSeries(h.asset_a,start,end),vm=new Map(v.map(x=>[Date.parse(x.observed_at),Number(x.volume_base)])),pv:VolumePoint[]=a.filter(x=>vm.has(x.t)).map(x=>({ts:new Date(x.t).toISOString(),price:x.p,volume:vm.get(x.t)!}));for(const hz of horizons){const vals:number[]=[];for(let i=24;i+hz<pv.length;i++){const z=volumeTrigger(h.trigger_definition.family,pv,i);if(z.trigger)vals.push(ret(pv[i].price,pv[i+hz].price)*z.dir)}const mu=mean(vals);results[hz]={n:vals.length,meanDirectionalReturn:mu,winRate:vals.length?vals.filter(x=>x>0).length/vals.length:null};if(vals.length>=30&&mu!=null&&(!best||mu>best.meanDirectionalReturn))best={horizon:hz,n:vals.length,meanDirectionalReturn:mu,winRate:results[hz].winRate}}}
 const verdict=!best?"INCONCLUSIVE":best.meanDirectionalReturn>0?"PASS":"FAIL";return{verdict,n:best?.n??0,best,allHorizons:results,family:h.trigger_definition?.family}}
async function main(){const {data,error}=await db.from("hypotheses").select("id,hypothesis_key,asset_a,asset_b,trigger_definition,predicted_effect,status").eq("status","PROPOSED").or("retry_after.is.null,retry_after.lte."+new Date().toISOString()).limit(50);if(error)throw error;let pass=0,fail=0,inc=0;
 for(const h of(data??[]) as H[]){const r=await test(h);r.verdict==="PASS"?pass++:r.verdict==="FAIL"?fail++:inc++;const {error:te}=await db.from("hypothesis_tests").insert({hypothesis_id:h.id,test_type:"DISCOVERY",dataset_start:new Date(Date.now()-180*24*3600_000).toISOString(),dataset_end:new Date().toISOString(),code_version:"build-041-v1",assumptions:{familyAware:true,dataSource:"HIST-028 only, paginated",horizonsHours:[1,4,8,12,24],minimumEvents:30,costs:"applied at adversarial stage"},sample_size:r.n,result:r,verdict:r.verdict});if(te)throw te;let status=r.verdict==="PASS"?"TESTING":r.verdict==="FAIL"?"REJECTED":"PROPOSED";let patch:any={status,updated_at:new Date().toISOString(),retry_after:null,retry_reason:null};
 if(r.verdict==="INCONCLUSIVE"){const {data:cur,error:ce}=await db.from("hypotheses").select("inconclusive_count").eq("id",h.id).single();if(ce)throw ce;const n=Number(cur?.inconclusive_count??0)+1,days=Math.min(30,Math.max(1,2**Math.min(n-1,5))),retry=new Date(Date.now()+days*86400_000).toISOString();patch={...patch,retry_after:retry,retry_reason:"Insufficient qualifying historical events; retry only after cooldown/new evidence.",evidence_count_at_retry:r.n,inconclusive_count:n};const {error:re}=await db.from("research_retry_events").insert({hypothesis_id:h.id,prior_status:"PROPOSED",next_retry_at:retry,reason:patch.retry_reason,evidence_count:r.n,details:{inconclusiveCount:n,cooldownDays:days,family:r.family}});if(re)throw re}
 const {error:ue}=await db.from("hypotheses").update(patch).eq("id",h.id);if(ue)throw ue}
 console.log(JSON.stringify({ok:true,build:"041",tested:(data??[]).length,pass,fail,inconclusive:inc,authorizedToTrade:false},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
