import { db } from "./db.js";import {volumeTrigger,type VolumePoint} from "./discovery/volumeLibrary.js";
import { adversarialReview } from "./discovery/adversarialScientist.js";
import { ret, singleEvents, pairEvents, type Pt } from "./science/priceEvents.js";
type H={id:string;asset_a:string;asset_b:string|null;trigger_definition:any;status:string};
// Build 041: (1) page past Supabase's 1,000-row cap and read only the HIST-028 backfill;
// (2) prosecute at the horizon the Discovery Test selected, not always 4h;
// (3) vals is reassignable (the volume branch previously threw "Assignment to constant variable").
const PAGE=1000;
async function series(asset:string,start:string,end:string):Promise<Pt[]>{const rows:any[]=[];for(let f=0;;f+=PAGE){const {data,error}=await db.from("crypto_universe_snapshots").select("observed_at,price_usd").eq("asset",asset).eq("sensor_version","HIST-028").gte("observed_at",start).lte("observed_at",end).order("observed_at",{ascending:true}).range(f,f+PAGE-1);if(error)throw error;rows.push(...(data??[]));if((data??[]).length<PAGE)break}return rows.map(x=>({t:Date.parse(x.observed_at),p:Number(x.price_usd)}))}
async function volumeSeries(asset:string,start:string,end:string){const rows:any[]=[];for(let f=0;;f+=PAGE){const {data,error}=await db.from("market_volume_observations").select("observed_at,volume_base").eq("asset",asset).eq("sensor_version","VOL035").gte("observed_at",start).lte("observed_at",end).order("observed_at",{ascending:true}).range(f,f+PAGE-1);if(error)throw error;rows.push(...(data??[]));if((data??[]).length<PAGE)break}return rows}
async function main(){const {data,error}=await db.from("hypotheses").select("id,asset_a,asset_b,trigger_definition,status").eq("status","TESTING").limit(500);if(error)throw error;let passed=0,failed=0,inconclusive=0;
 for(const h of(data??[]) as H[]){const {data:gate,error:ge}=await db.from("hypothesis_tests").select("fdr_pass,result").eq("hypothesis_id",h.id).eq("test_type","DISCOVERY").order("created_at",{ascending:false}).limit(1).single();if(ge)throw ge;if(gate?.fdr_pass!==true)continue;const end=new Date().toISOString(),start=new Date(Date.now()-180*24*3600_000).toISOString(),a=await series(h.asset_a,start,end),b=h.asset_b?await series(h.asset_b,start,end):null,hz=Number(gate?.result?.best?.horizon??4);let vals=b?pairEvents(h.trigger_definition?.family,a,b,hz):singleEvents(h.trigger_definition?.family,a,hz);if(["VOLUME_SPIKE","MOMENTUM_VOLUME_CONFIRMATION","MOMENTUM_VOLUME_DIVERGENCE","VOLUME_PRECEDES_PRICE"].includes(h.trigger_definition?.family)){const v=await volumeSeries(h.asset_a,start,end),vm=new Map(v.map(x=>[Date.parse(x.observed_at),Number(x.volume_base)])),pv:VolumePoint[]=a.filter(x=>vm.has(x.t)).map(x=>({ts:new Date(x.t).toISOString(),price:x.p,volume:vm.get(x.t)!}));vals=[];for(let i=24;i+hz<pv.length;i++){const z=volumeTrigger(h.trigger_definition.family,pv,i);if(z.trigger)vals.push(ret(pv[i].price,pv[i+hz].price)*z.dir)}}
  const review=adversarialReview({sampleSize:vals.length,returns:vals,costBps:50});review.verdict==="PASS"?passed++:review.verdict==="FAIL"?failed++:inconclusive++;
  const {error:te}=await db.from("hypothesis_tests").insert({hypothesis_id:h.id,test_type:"ADVERSARIAL",dataset_start:start,dataset_end:end,code_version:"build-041-v1",assumptions:{familyAware:true,horizonHours:hz,horizonSource:"discovery best horizon",dataSource:"HIST-028 only, paginated",roundTripCostBps:50,review:"sample,median,outlier-dependence,costs"},sample_size:vals.length,result:review,verdict:review.verdict});if(te)throw te;
  const status=review.verdict==="PASS"?"HISTORICAL_SURVIVOR":review.verdict==="FAIL"?"REJECTED":"TESTING";const {error:ue}=await db.from("hypotheses").update({status,updated_at:new Date().toISOString(),frozen_at:review.verdict==="PASS"?new Date().toISOString():null}).eq("id",h.id);if(ue)throw ue}
 console.log(JSON.stringify({ok:true,build:"041",repairedBuild:"030",reviewed:(data??[]).length,passed,failed,inconclusive,authorizedToTrade:false},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
